'use strict';

var React = require('react-native');
var Immutable = require('immutable');

var words = Immutable.Map({
                  "aaa":"Authentication Authorization",
                  "aabb":"Axis Aligned Bounding Box",
                  "aac":"Advanced Audio Coding",
                  "aal":"ATM Adaptation Layer",
                  "aalc":"ATM Adaptation Layer Connection",
                  "aarp":"AppleTalk Address Resolution Protocol",
                  "abcl":"Actor-Based Concurrent Language",
                  "abi":"Application Binary Interface",
                  "abm":"Asynchronous Balanced Mode",
                  "abr":"Area Border Router",
                  "abr":"Auto Baud-Rate detection",
                  "abr":"Available Bitrate",
                  "abr":"Average Bitrate",
                  "ac":"Acoustic Coupler",
                  "ac":"Alternating Current",
                  "acd":"Automatic Call Distributor",
                  "ace":"Advanced Computing Environment",
                  "acid":"Atomicity Consistency Isolation Durability",
                  "ack":"ACKnowledgement",
                  "ack":"Amsterdam Compiler Kit",
                  "acl":"Access Control List",
                  "acl":"Active Current Loop",
                  "acm":"Association for Computing Machinery",
                  "acme":"Automated Classification of Medical Entities",
                  "acp":"Airline Control Program",
                  "acpi":"Advanced Configuration and Power Interface",
                  "acr":"Allowed Cell Rate",
                  "acr":"Attenuation to Crosstalk Ratio",
                  "ad":"Active Directory",
                  "ad":"Administrative Domain",
                  "adc":"Analog-to-Digital Converter",
                  "adc":"Apple Display Connector",
                  "adb":"Apple Desktop Bus",
                  "adccp":"Advanced Data Communications Control Procedures",
                  "ado":"ActiveX Data Objects",
                  "adsl":"Asymmetric Digital Subscriber Line",
                  "adt":"Abstract Data Type",
                  "ae":"Adaptive Equalizer",
                  "aes":"Advanced Encryption Standard",
                  "af":"Anisotropic Filtering",
                  "afp":"Apple Filing Protocol",
                  "agp":"Accelerated Graphics Port",
                  "ah":"Active Hub",
                  "ai":"Artificial Intelligence",
                  "aix":"Advanced Interactive eXecutive",
                  "ajax":"Asynchronous JavaScript and XML",
                  "al":"Active Link",
                  "al":"Access List",
                  "alac":"Apple Lossless Audio Codec",
                  "algol":"Algorithmic Language",
                  "alsa":"Advanced Linux Sound Architecture",
                  "alu":"Arithmetic and Logical Unit",
                  "am":"Access Method",
                  "am":"Active Matrix",
                  "amoled":"Active-Matrix Organic Light-Emitting Diode",
                  "am":"Active Monitor",
                  "am":"Allied Mastercomputer",
                  "am":"Amplitude Modulation",
                  "amd":"Advanced Micro Devices",
                  "amqp":"Advanced Message Queuing Protocol",
                  "amr":"Audio Modem Riser",
                  "ann":"Artificial Neural Network",
                  "ansi":"American National Standards Institute",
                  "ant":"Another Neat Tool",
                  "aoe":"ATA over Ethernet",
                  "aop":"Aspect-Oriented Programming",
                  "apci":"Application-Layer Protocol Control Information",
                  "api":"Application Programming Interface",
                  "apic":"Advanced Programmable Interrupt Controller",
                  "apipa":"Automatic Private IP Addressing",
                  "apl":"A Programming Language",
                  "apr":"Apache Portable Runtime",
                  "arc":"Adaptive Replacement Cache",
                  "arc":"Advanced RISC Computing",
                  "arin":"American Registry for Internet Numbers",
                  "arm":"Advanced RISC Machines",
                  "aros":"AROS Research Operating System",
                  "arp":"Address Resolution Protocol",
                  "arpa":"Address and Routing Parameter Area",
                  "arpa":"Advanced Research Projects Agency",
                  "arpanet":"Advanced Research Projects Agency Network",
                  "as":"Access Server",
                  "ascii":"American Standard Code for Information Interchange",
                  "asg":"Abstract Semantic Graph",
                  "asic":"Application-Specific Integrated Circuit",
                  "asimo":"Advanced Step in Innovative Mobility",
                  "aslr":"Address Space Layout Randomization",
                  "asm":"Algorithmic State Machine",
                  "asmp":"Asymmetric Multiprocessing",
                  "asn.1":"Abstract Syntax Notation 1",
                  "asp":"Active Server Pages",
                  "asp":"Application Service Provider",
                  "asr":"Asynchronous Signal Routine",
                  "ast":"Abstract Syntax Tree",
                  "assp":"Application-Specific Standard Product",
                  "at":"Advanced Technology",
                  "at":"Access Time",
                  "at":"Active Terminator",
                  "ata":"Advanced Technology Attachment",
                  "atag":"Authoring Tool Accessibility Guidelines",
                  "atapi":"Advanced Technology Attachment Packet Interface",
                  "atm":"Asynchronous Transfer Mode",
                  "avc":"Advanced Video Coding",
                  "avi":"Audio Video Interleaved",
                  "awk":"Aho Weinberger Kernighan",
                  "awt":"Abstract Window Toolkit",
                  "b2b":"Business-to-Business",
                  "b2c":"Business-to-Consumer",
                  "bal":"Basic Assembly Language",
                  "bam":"Block Availability Map",
                  "bash":"Bourne-again shell",
                  "basic":"Beginner's All-Purpose Symbolic Instruction Code",
                  "bbp":"Baseband Processor",
                  "bbs":"Bulletin Board System",
                  "bcd":"Binary Coded Decimal",
                  "bcnf":"Boyceâ€“Codd normal form",
                  "beep":"Blocks Extensible Exchange Protocol",
                  "ber":"Bit Error Rate",
                  "bfd":"Bidirectional Forwarding Detection",
                  "bfd":"Binary File Descriptor",
                  "bfs":"Breadth-First Search",
                  "bft":"Byzantine Fault Tolerant",
                  "bgp":"Border Gateway Protocol",
                  "bi":"Business Intelligence",
                  "bidi":"Bi-Directional",
                  "bin":"binary",
                  "binac":"Binary Automatic Computer",
                  "bind":"Berkeley Internet Name Domain",
                  "bios":"Basic Input Output System",
                  "bjt":"Bipolar Junction Transistor",
                  "bit":"binary digit",
                  "blob":"Binary large object",
                  "blog":"Web Log",
                  "bmp":"Basic Multilingual Plane",
                  "bnc":"Bayonet Neill-Concelman",
                  "boinc":"Berkeley Open Infrastructure for Network Computing",
                  "bom":"Byte Order Mark",
                  "bootp":"Bootstrap Protocol",
                  "bpdu":"Bridge Protocol Data Unit",
                  "bpel":"Business Process Execution Language",
                  "bpl":"Broadband over Power Lines",
                  "bpm":"Business Process Management",
                  "bpm":"Business Process Modeling",
                  "bps":"bits per second",
                  "brm":"Business Reference Model",
                  "brms":"Business Rule Management System",
                  "brr":"Business Readiness Rating",
                  "bsa":"Business Software Alliance",
                  "bsb":"Backside Bus",
                  "bsd":"Berkeley Software Distribution",
                  "bsod":"Blue Screen of Death",
                  "bss":"Block Started by Symbol",
                  "bt":"BitTorrent",
                  "bt":"Bluetooth",
                  "b tam":"Basic Telecommunications Access Method",
                  "bw":"Bandwidth",
                  "byod":"Bring Your Own Device",
                  "ca":"Computer architecture",
                  "cad":"Computer-Aided Design",
                  "cae":"Computer-Aided Engineering",
                  "caid":"Computer-Aided Industrial Design",
                  "cai":"Computer-Aided Instruction",
                  "cam":"Computer-Aided Manufacturing",
                  "captcha":"Completely Automated Public Turing Test to tell Computers and Humans Apart",
                  "cat":"Computer-Aided Translation",
                  "caq":"Computer-Aided Quality Assurance",
                  "case":"Computer-Aided Software Engineering",
                  "cc":"C Compiler",
                  "cd":"Compact Disc",
                  "cde":"Common Desktop Environment",
                  "cdma":"Code Division Multiple Access",
                  "cdn":"Content Delivery Network",
                  "cdp":"Continuous Data Protection",
                  "cd-r":"CD-Recordable",
                  "cd-rom":"CD Read-Only Memory",
                  "cd-rw":"CD-Rewritable",
                  "cdsa":"Common Data Security Architecture",
                  "cert":"Computer Emergency Response Team",
                  "ces":"Consumer Electronics Show",
                  "cf":"Compact Flash",
                  "cfd":"Computational Fluid Dynamics",
                  "cfg":"Context-Free Grammar",
                  "cfg":"Control Flow Graph",
                  "cg":"Computer Graphics",
                  "cga":"Color Graphics Array",
                  "cgi":"Common Gateway Interface",
                  "cgi":"Computer-Generated Imagery",
                  "cgt":"Computational Graph Theory",
                  "chap":"Challenge-Handshake Authentication Protocol",
                  "chs":"Cylinder-Head-Sector",
                  "cidr":"Classless Inter-Domain Routing",
                  "cifs":"Common Internet Filesystem",
                  "cim":"Common Information Model",
                  "cim":"Computationally Independent Model",
                  "cir":"Committed information rate",
                  "cisc":"Complex Instruction Set Computer",
                  "cjk":"Chinese",
                  "cjkv":"Chinese",
                  "cli":"Command Line Interface",
                  "clr":"Common Language Runtime",
                  "cm":"Configuration Management",
                  "cm":"Content Management",
                  "cmmi":"Capability Maturity Model Integration",
                  "cmos":"Complementary Metal-Oxide Semiconductor",
                  "cms":"Content Management System",
                  "cn":"Canonical Name",
                  "cn":"Common Name",
                  "cnc":"Computer Numerical Control",
                  "cnr":"Communications and Networking Riser",
                  "cobol":"Common Business-Oriented Language",
                  "com":"Component Object Model",
                  "corba":"Common Object Request Broker Architecture",
                  "cots":"Commercial Off-The-Shelf",
                  "cpa":"Cell Processor Architecture",
                  "cpan":"Comprehensive Perl Archive Network",
                  "cp/m":"Control Program/Monitor",
                  "cpri":"Common Public Radio Interface",
                  "cps":"characters per second",
                  "cpu":"Central Processing Unit",
                  "cr":"Carriage Return",
                  "cran":"Comprehensive R Archive Network",
                  "crc":"Cyclic Redundancy Check",
                  "crlf":"Carriage Return Line Feeds",
                  "crm":"Customer Relationship Management",
                  "crs":"Computer Reservations System",
                  "crt":"Cathode Ray Tube",
                  "crud":"Create",
                  "cs":"Cable Select",
                  "cs":"Computer Science",
                  "cse":"Computer Science and Engineering",
                  "csi":"Common System Interface",
                  "csp":"Cloud Service Provider",
                  "csp":"Communicating Sequential Processes",
                  "csrf":"Cross-Site Request Forgery",
                  "css":"Cascading Style Sheets",
                  "css":"Content-Scrambling System",
                  "css":"Closed Source Software",
                  "css":"Cross-Site Scripting",
                  "csv":"Comma-Separated Values",
                  "ct":"Computerized Tomography",
                  "ctan":"Comprehensive TeX Archive Network",
                  "ctcp":"Client-To-Client Protocol",
                  "cti":"Computer Telephony Integration",
                  "ctfe-compile time function execution":"",
                  "ctl":"Computational Tree Logic",
                  "ctm":"Close To Metal",
                  "cts":"Clear To Send",
                  "ctss":"Compatible Time-Sharing System",
                  "cua":"Common User Access",
                  "cvs":"Concurrent Versioning System",
                  "dac":"Digital-To-Analog Converter",
                  "dac":"Discretionary Access Control",
                  "dal":"Database Abstraction Layer",
                  "dao":"Data Access Object",
                  "dao":"Data Access Objects",
                  "dao":"Disk-At-Once",
                  "dap":"Directory Access Protocol",
                  "darpa":"Defense Advanced Research Projects Agency",
                  "dat":"Digital Audio Tape",
                  "db":"Database",
                  "dba":"Database Administrator",
                  "dbcs":"Double Byte Character Set",
                  "dbms":"Database Management System",
                  "dcc":"Direct Client-to-Client",
                  "dccp":"Datagram Congestion Control Protocol",
                  "dcca":"Debian Common Core Alliance",
                  "dcl":"Data Control Language",
                  "dcs":"Distributed Control System",
                  "dcmi":"Dublin Core Metadata Initiative",
                  "dcom":"Distributed Component Object Model",
                  "dd":"Double Density",
                  "dde":"Dynamic Data Exchange",
                  "ddl":"Data Definition Language",
                  "ddos":"Distributed Denial of Service",
                  "ddr":"Double Data Rate",
                  "dec":"Digital Equipment Corporation",
                  "des":"Data Encryption Standard",
                  "dev":"development",
                  "dfa":"Deterministic Finite Automaton",
                  "dfd":"Data Flow Diagram",
                  "dfs":"Depth-First Search",
                  "dfs":"Distributed File System",
                  "dgd":"Dworkin's Game Driver",
                  "dhcp":"Dynamic Host Configuration Protocol",
                  "dhtml":"Dynamic Hypertext Markup Language",
                  "dif":"Data Integrity Field",
                  "dimm":"Dual Inline Memory Module",
                  "din":"Deutsches Institut fÃ¼r Normung",
                  "dip":"Dual In-line Package",
                  "divx":"Digital Video Express",
                  "dkim":"Domain Keys Identified Mail",
                  "dl":"Download",
                  "dll":"Dynamic Link Library",
                  "dlna":"Digital Living Network Alliance",
                  "dlp":"Data loss protection",
                  "dma":"Direct Memory Access",
                  "dmca":"Digital Millennium Copyright Act",
                  "dmi":"Direct Media Interface",
                  "dml":"Data Manipulation Language",
                  "dml":"Definitive Media Library",
                  "dmr":"Dennis M. Ritchie",
                  "dmz":"Demilitarized Zone",
                  "dn":"Distinguished Name",
                  "dnd":"Drag-and-Drop",
                  "dns":"Domain Name System",
                  "doa":"Dead on Arrival",
                  "docsis":"Data Over Cable Service Interface Specification",
                  "dom":"Document Object Model",
                  "dos":"Denial of Service",
                  "dos":"Disk Operating System",
                  "dp":"Dot Pitch",
                  "dpc":"Deferred Procedure Call",
                  "dpi":"Deep Packet Inspection",
                  "dpi":"Dots Per Inch",
                  "dpmi":"DOS Protected Mode Interface",
                  "dpms":"Display Power Management Signaling",
                  "dram":"Dynamic Random Access Memory",
                  "dr-dos":"Digital Research - Disk Operating System",
                  "dri":"Direct Rendering Infrastructure",
                  "drm":"Digital Rights Management",
                  "drm":"Direct Rendering Manager",
                  "dsaâ€“digital signature algorithm":"",
                  "dsdl":"Document Schema Definition Languages",
                  "dsdm":"Dynamic Systems Development Method",
                  "dsl":"Digital Subscriber Line",
                  "dsl":"Domain-Specific Language",
                  "dslam":"Digital Subscriber Line Access Multiplexer",
                  "dsn":"Database Source Name",
                  "dsn":"Data Set Name",
                  "dsp":"Digital Signal Processor",
                  "dsssl":"Document Style Semantics and Specification Language",
                  "dtd":"Document Type Definition",
                  "dte":"Data Terminal Equipment",
                  "dtp":"Desktop Publishing",
                  "dtr":"Data Terminal Ready",
                  "dvd":"Digital Versatile Disc",
                  "dvd-r":"DVD-Recordable",
                  "dvd-rom":"DVD-Read Only Memory",
                  "dvd-rw":"DVD-Rewritable",
                  "dvi":"Digital Visual Interface",
                  "dvr":"Digital Video Recorder",
                  "dw":"Data Warehouse",
                  "eai":"Enterprise Application Integration",
                  "eap":"Extensible Authentication Protocol",
                  "ebcdic":"Extended Binary Coded Decimal Interchange Code",
                  "ebml":"Extensible Binary Meta Language",
                  "ecc":"Elliptic Curve Cryptography",
                  "ecma":"European Computer Manufacturers Association",
                  "ecn":"Explicit Congestion Notification",
                  "ecos":"Embedded Configurable Operating System",
                  "ecrs":"Expense and Cost Recovery System",
                  "eda":"Electronic Design Automation",
                  "edi":"Electronic Data Interchange",
                  "edo":"Extended Data Out",
                  "edsac":"Electronic Delay Storage Automatic Calculator",
                  "edvac":"Electronic Discrete Variable Automatic Computer",
                  "eeprom":"Electronically Erasable Programmable Read-Only Memory",
                  "eff":"Electronic Frontier Foundation",
                  "efi":"Extensible Firmware Interface",
                  "efm":"Eight-to-Fourteen Modulation",
                  "ega":"Enhanced Graphics Array",
                  "e-mail":"Electronic mail",
                  "egp":"Exterior Gateway Protocol",
                  "eid":"electronic ID card",
                  "eide":"Enhanced IDE",
                  "eigrp":"Enhanced Interior Gateway Routing Protocol",
                  "eisa":"Extended Industry Standard Architecture",
                  "elf":"Extremely Low Frequency",
                  "elf":"Executable and Linkable Format",
                  "elm":"ELectronic Mail",
                  "emacs":"Editor MACroS",
                  "ems":"Expanded Memory Specification",
                  "eniac":"Electronic Numerical Integrator And Computer",
                  "eod":"End of Day",
                  "eof":"End of File",
                  "eol":"End of Line",
                  "eom":"End Of Message",
                  "epic":"Explicitly Parallel Instruction Computing",
                  "eprom":"Erasable Programmable Read-Only Memory",
                  "erd":"Entity-Relationship Diagram",
                  "erm":"Entity-Relationship Model",
                  "erp":"Enterprise Resource Planning",
                  "esb":"Enterprise service bus",
                  "escon":"Enterprise Systems Connection",
                  "esd":"Electrostatic Discharge",
                  "etl":"Extract",
                  "esr":"Eric Steven Raymond",
                  "euc":"Extended Unix Code",
                  "eula":"End User License Agreement",
                  "ewmh":"Extended Window Manager Hints",
                  "ext":"EXTended file system",
                  "fap":"FORTRAN Assembly Program",
                  "fasm":"Flat ASseMbler",
                  "fat":"File Allocation Table",
                  "faq":"Frequently Asked Questions",
                  "fbdimm":"Fully Buffered Dual Inline Memory Module",
                  "fc-al":"Fibre Channel Arbitrated Loop",
                  "fcb":"File Control Block",
                  "fcs":"Frame Check Sequence",
                  "fdc":"Floppy Disk Controller",
                  "fds":"Fedora Directory Server",
                  "fdd":"Floppy Disk Drive",
                  "fddi":"Fiber Distributed Data Interface",
                  "fdma":"Frequency-Division Multiple Access",
                  "fec":"Forward Error Correction",
                  "femb":"Front-End Motherboard",
                  "fet":"Field Effect Transistor",
                  "fhs":"Filesystem Hierarchy Standard",
                  "ficon":"FIber CONnectivity",
                  "fifo":"First In First Out",
                  "fips":"Federal Information Processing Standards",
                  "fl":"Function Level",
                  "flac":"Free Lossless Audio Codec",
                  "flops":"FLoating-Point Operations Per Second",
                  "floss":"Free/Libre/Open Source Software",
                  "fmc":" Fixed Mobile Convergence Mobile UC or Unified Communications over Wireless",
                  "foldoc":"Free On-line Dictionary of Computing",
                  "fosdem":"Free and Open source Software Developers' European Meeting",
                  "fosi":"Formatted Output Specification Instance",
                  "foss":"Free and Open Source Software",
                  "fp":"Function Programming",
                  "fpga":"Field Programmable Gate Array",
                  "fps":"Floating Point Systems",
                  "fpu":"Floating Point Unit",
                  "fru":"Field Replaceable Unit",
                  "fs":"File System",
                  "fsb":"Front Side Bus",
                  "fsck":"File System Check",
                  "fsf":"Free Software Foundation",
                  "fsm":"Finite State Machine",
                  "fttc":"Fiber To The Curb",
                  "ftth":"Fiber To The Home",
                  "fttp":"Fiber To The Premises",
                  "ftp":"File Transfer Protocol",
                  "fqdn":"Fully Qualified Domain Name",
                  "fud":"Fear Uncertainty Doubt",
                  "fws":"Folding White Space",
                  "fxp":"File eXchange Protocol",
                  "fyi":"For Your Information",
                  "g11n":"Globalization",
                  "gas":"GNU Assembler",
                  "gb":"Gigabit",
                  "gb":"Gigabyte",
                  "gcc":"GNU Compiler Collection",
                  "gcj":"GNU Compiler for Java",
                  "gcr":"Group Code Recording",
                  "gdb":"GNU Debugger",
                  "gdi":"Graphics Device Interface",
                  "gfdl":"GNU Free Documentation License",
                  "gif":"Graphics Interchange Format",
                  "gigo":"Garbage In",
                  "gimp":"GNU Image Manipulation Program",
                  "gimps":"Great Internet Mersenne Prime Search",
                  "gis":"Geographic Information System",
                  "glut":"OpenGL Utility Toolkit",
                  "gml":"Geography Markup Language",
                  "gnome":"GNU Network Object Model Environment",
                  "gnu":"GNU's Not Unix",
                  "goms":"Goals",
                  "gpasm":"GNU PIC ASseMbler",
                  "gpfs":"General Parallel File System",
                  "gpg":"GNU Privacy Guard",
                  "gpgpu":"General-Purpose Computing on Graphics Processing Units",
                  "gpib":"General-Purpose Instrumentation Bus",
                  "gpl":"General Public License",
                  "gpl":"General-Purpose Language",
                  "gprs":"General Packet Radio Service",
                  "gpt":"GUID Partition Table",
                  "gpu":"Graphics Processing Unit",
                  "grub":"Grand Unified Boot-Loader",
                  "gsm":"Global System for Mobile Communications",
                  "gtk+":"GIMP Toolkit",
                  "gui":"Graphical User Interface",
                  "guid":"Globally Unique IDentifier",
                  "gwt":"Google Web Toolkit",
                  "ha":"High Availability",
                  "hal":"Hardware Abstraction Layer",
                  "hba":"Host Bus Adapter",
                  "hci":"Human Computer Interaction",
                  "hd":"High Density",
                  "hdd":"Hard Disk Drive",
                  "hcl":"Hardware Compatibility List",
                  "hd dvd":"High Definition DVD",
                  "hdl":"Hardware Description Language",
                  "hdmi":"High-Definition Multimedia Interface",
                  "hf":"High Frequency",
                  "hfs":"Hierarchical File System",
                  "hhd":"Hybrid Hard Drive",
                  "hid":"Human Interface Device",
                  "hig":"Human Interface Guidelines",
                  "hird":"Hurd of Interfaces Representing Depth",
                  "hlasm":"High Level ASseMbler",
                  "hma":"High Memory Area",
                  "hp":"Hewlett-Packard",
                  "hpc":"High-Performance Computing",
                  "hpfs":"High Performance File System",
                  "hsdpa":"High-Speed Downlink Packet Access",
                  "htc":"High-Throughput Computing",
                  "hsm":"Hierarchical Storage Management",
                  "ht":"Hyper Threading",
                  "htm":"Hierarchical Temporal Memory",
                  "html":"Hypertext Markup Language",
                  "http":"Hypertext Transfer Protocol",
                  "httpd":"Hypertext Transport Protocol Daemon",
                  "htx":"HyperTransport eXpansion",
                  "hurd":"Hird of Unix-Replacing Daemons",
                  "hvd":"Holographic Versatile Disc",
                  "hz":"Hertz",
                  "iâ²c":"Inter-Integrated Circuit",
                  "i18n":"Internationalization",
                  "iana":"Internet Assigned Numbers Authority",
                  "ibcs":"Intel Binary Compatibility Standard",
                  "ibm":"International Business Machines",
                  "ic":"Integrated Circuit",
                  "icann":"Internet Corporation for Assigned Names and Numbers",
                  "ice":"In-Circuit Emulator",
                  "ice":"Intrusion Countermeasure Electronics",
                  "icmp":"Internet Control Message Protocol",
                  "icp":"Internet Cache Protocol",
                  "ict":"Information and Communication Technology",
                  "ide":"Integrated Development Environment",
                  "ide":"Integrated Drive Electronics",
                  "idf":"Intermediate Distribution Frame",
                  "idl":"Interface Definition Language",
                  "ids":"Intrusion Detection System",
                  "ie":"Internet Explorer",
                  "iec":"International Electrotechnical Commission",
                  "ieee":"Institute of Electrical and Electronics Engineers",
                  "ietf":"Internet Engineering Task Force",
                  "ifl":"Integrated Facility for Linux",
                  "igmp":"Internet Group Management Protocol",
                  "igrp":"Interior Gateway Routing Protocol",
                  "ihv":"Independent Hardware Vendor",
                  "iiop":"Internet Inter-Orb Protocol",
                  "iis":"Internet Information Services",
                  "il":"Intermediate Language",
                  "im":"Instant Messaging",
                  "imap":"Internet Message Access Protocol",
                  "ime":"Input Method Editor",
                  "infosec":"Information Systems Security",
                  "i/o":"Input/output",
                  "iot":"Internet of Things",
                  "ip":"Intellectual Property",
                  "ip":"Internet Protocol",
                  "ipc":"Inter-Process Communication",
                  "ipl":"Initial Program Load",
                  "ipo":"Inter Procedural Optimization",
                  "ipp":"Internet Printing Protocol",
                  "ips":"In-Plane Switching",
                  "ips":"Instructions Per Second",
                  "ips":"Intrusion Prevention System",
                  "ipsec":"Internet Protocol security",
                  "iptv":"Internet Protocol Television",
                  "ipx":"Internetwork Packet Exchange",
                  "ir":"Intermediate Representation",
                  "irc":"Internet Relay Chat",
                  "irda":"Infrared Data Association",
                  "iri":"Internationalized Resource Identifier",
                  "irp":"I/O Request Packet",
                  "irq":"Interrupt Request",
                  "is":"Information Systems",
                  "is-is":"Intermediate System to Intermediate System",
                  "isa":"Industry Standard Architecture",
                  "isa":"Instruction Set Architecture",
                  "isam":"Indexed Sequential Access Method",
                  "isc":"Internet Storm Center",
                  "iscsi":"Internet Small Computer System Interface",
                  "isdn":"Integrated Services Digital Network",
                  "iso":"International Organization for Standardization",
                  "isns":"Internet Storage Name Service",
                  "isp":"Internet Service Provider",
                  "ispf":"Interactive System Productivity Facility",
                  "isr":"Interrupt Service Routine",
                  "isv":"Independent Software Vendor",
                  "it":"Information Technology",
                  "itil":"Information Technology Infrastructure Library",
                  "itl":"Interval Temporal Logic",
                  "itu":"International Telecommunication Union",
                  "ivrs":"Interactive Voice Response System",
                  "ivcr":"Interactive Virtual Classroom",
                  "j2ee":"Java 2 Enterprise Edition",
                  "j2me":"Java 2 Micro Edition",
                  "j2se":"Java 2 Standard Edition",
                  "jaxb":"Java Architecture for XML Binding",
                  "jax-rpc":"Java XML for Remote Procedure Calls",
                  "jaxp":"Java API for XML Processing",
                  "jbod":"Just a Bunch of Disks",
                  "jce":" Java Cryptography Extension",
                  "jcl":"Job Control Language",
                  "jcp":"Java Community Process",
                  "jdbc":"Java Database Connectivity",
                  "jdk":"Java Development Kit",
                  "jee":"Java Enterprise Edition",
                  "jes":"Job Entry Subsystem",
                  "jds":"Java Desktop System",
                  "jfc":"Java Foundation Classes",
                  "jfet":"Junction Field-Effect Transistor",
                  "jfs":"IBM Journaling File System",
                  "jini":"Jini Is Not Initials",
                  "jit":"Just-In-Time",
                  "jme":"Java Micro Edition",
                  "jmx":"Java Management Extensions",
                  "jms":"Java Message Service",
                  "jndi":"Java Naming and Directory Interface",
                  "jni":"Java Native Interface",
                  "jnz":"Jump non-zero",
                  "jpeg":"Joint Photographic Experts Group",
                  "jre":"Java Runtime Environment",
                  "js":"JavaScript",
                  "jse":"Java Standard Edition",
                  "json":"JavaScript Object Notation",
                  "jsp":"Jackson Structured Programming",
                  "jsp":"JavaServer Pages",
                  "jtag":"Joint Test Action Group",
                  "jug":"Java Users Group",
                  "jvm":"Java Virtual Machine",
                  "kb":"Keyboard",
                  "kb":"Kilobit",
                  "kb":"Kilobyte",
                  "kb":"Knowledge Base",
                  "kde":"K Desktop Environment",
                  "khz":"Kilohertz",
                  "km":"Knowledge Machine",
                  "krl":"Knowledge Representation Language",
                  "kvm":"Keyboard",
                  "l10n":"Localization",
                  "l2tp":"Layer two Tunneling Protocol",
                  "lamp":"Linux Apache MySQL Perl",
                  "lamp":"Linux Apache MySQL PHP",
                  "lamp":"Linux Apache MySQL Python",
                  "lan":"Local Area Network",
                  "lba":"Logical Block Addressing",
                  "lcd":"Liquid Crystal Display",
                  "lcr":"Least Cost Routing",
                  "lcos":"Liquid Crystal On Silicon",
                  "ldap":"Lightweight Directory Access Protocol",
                  "le":"Logical Extents",
                  "led":"Light-Emitting Diode",
                  "lf":"Line Feed",
                  "lf":"Low Frequency",
                  "lfs":"Linux From Scratch",
                  "lgpl":"Lesser General Public License",
                  "lib":"LIBrary",
                  "lif":"Low Insertion Force",
                  "lifo":"Last In First Out",
                  "lilo":"Linux Loader",
                  "lisp":"LISt Processing",
                  "lkml":"Linux Kernel Mailing List",
                  "lm":"Lan Manager",
                  "loc":"Lines of Code",
                  "lpc":"Lars PensjÃ¶ C",
                  "lpi":"Linux Professional Institute",
                  "lpt":" Line Print Terminal",
                  "lsb":"Least Significant Bit",
                  "lsb":"Linux Standard Base",
                  "lsi":"Large-Scale Integration",
                  "ltl":"Linear Temporal Logic",
                  "ltr":"Left-to-Right",
                  "lug":"Linux User Group",
                  "lun":"Logical Unit Number",
                  "lv":"Logical Volume",
                  "lvd":"Low Voltage Differential",
                  "lvm":"Logical Volume Management",
                  "lzw":"Lempel-Ziv-Welch",
                  "lga":"Land Grid Array",
                  "mac":"Mandatory Access Control",
                  "mac":"Media Access Control",
                  "man":"Metropolitan Area Network",
                  "manet":"Mobile Ad-Hoc Network",
                  "mapi":"Messaging Application Programming Interface",
                  "mb":"Megabit",
                  "mb":"Megabyte",
                  "mbcs":"Multi Byte Character Set",
                  "mbd":"Model-Based Design",
                  "mbr":"Master Boot Record",
                  "mca":"Micro Channel Architecture",
                  "mca":"Microsoft Certified Architect",
                  "mcad":"Microsoft Certified Application Developer",
                  "mcas":"Microsoft Certified Application Specialist",
                  "mcdba":"Microsoft Certified DataBase Administrator",
                  "mcdst":"Microsoft Certified Desktop Support Technician",
                  "mcitp":"Microsoft Certified Information Technology Professional",
                  "mcm":"Microsoft Certified Master",
                  "mcp":"Microsoft Certified Professional",
                  "mcpd":"Microsoft Certified Professional Developer",
                  "mcsa":"Microsoft Certified Systems Administrator",
                  "mcsd":"Microsoft Certified Solution Developer",
                  "mcse":"Microsoft Certified Systems Engineer",
                  "mct":"Microsoft Certified Trainer",
                  "mcts":"Microsoft Certified Technology Specialist",
                  "mda":"Mail Delivery Agent",
                  "mda":"Model-Driven Architecture",
                  "mda":"Monochrome Display Adapter",
                  "mdd/mdsd":"Model-Driven (Software) Development",
                  "mdf":"Main Distribution Frame",
                  "mdi":"Multiple Document Interface",
                  "me":"[Windows] Millennium Edition",
                  "mf":"Medium Frequency",
                  "mfc":"Microsoft Foundation Classes",
                  "mfm":"Modified Frequency Modulation",
                  "mgcp":"Media Gateway Control Protocol",
                  "mhz":"Megahertz",
                  "mib":"Management Information Base",
                  "micr":"Magnetic Ink Character Recognition",
                  "midi":"Musical Instrument Digital Interface",
                  "mimd":"Multiple Instruction",
                  "mimo":"Multiple-Input Multiple-Output",
                  "minix":"MIni-uNIX",
                  "mips":"Million Instructions Per Second",
                  "mips":"Microprocessor without Interlocked Pipeline Stages",
                  "mis":"Management Information Systems",
                  "misd":"Multiple Instruction",
                  "mit":"Massachusetts Institute of Technology",
                  "mime":"Multipurpose Internet Mail Extensions",
                  "mmds":"Mortality Medical Data System",
                  "mmi":"Man Machine Interface.",
                  "mmio":"Memory-Mapped I/O",
                  "mmorpg":"Massively Multiplayer Online Role-Playing Game",
                  "mmu":"Memory Management Unit",
                  "mmx":"Multi-Media Extensions",
                  "mng":"Multiple-image Network Graphics",
                  "mobo":"Motherboard",
                  "mom":"Message-Oriented Middleware",
                  "moo":"MUD Object Oriented",
                  "mop":"Meta-Object Protocol",
                  "mos":"Microsoft Office Specialist",
                  "mosfet":"Metal-Oxide Semiconductor Field Effect Transistor",
                  "motd":"Message Of The Day",
                  "mous":"Microsoft Office User Specialist",
                  "mpaa":"Motion Picture Association of America",
                  "mpeg":"Motion Pictures Experts Group",
                  "mpl":"Mozilla Public License",
                  "mpls":"Multiprotocol Label Switching",
                  "mpu":"Microprocessor Unit",
                  "ms":"Memory Stick",
                  "ms":"Microsoft",
                  "msb":"Most Significant Bit",
                  "ms-dos":"Microsoft DOS",
                  "mt":"Machine Translation",
                  "mta":"Mail Transfer Agent",
                  "mta":"Microsoft Technology Associate",
                  "mtbf":"Mean Time Between Failures",
                  "mtu":"Maximum Transmission Unit",
                  "msa":"Mail Submission Agent",
                  "msdn":"Microsoft Developer Network",
                  "msi":"Medium-Scale Integration",
                  "msi":"Message Signaled Interrupt",
                  "msi":"Microsoft Installer",
                  "mua":"Mail User Agent",
                  "mud":"Multi-User Dungeon",
                  "mvc":"Model-View-Controller",
                  "mvp":"Most Valuable Professional",
                  "mvs":"Multiple Virtual Storage",
                  "mwcâ€“mobile world congress":"",
                  "mx":"Mail exchange",
                  "mxf":"Material Exchange Format",
                  "nack":"Negative ACKnowledgement",
                  "nak":"Negative AcKnowledge Character",
                  "nan":"Not a Number",
                  "nas":"Network-Attached Storage",
                  "nasm":"Netwide ASseMbler",
                  "nat":"Network Address Translation",
                  "ncp":"NetWare Core Protocol",
                  "ncq":"Native Command Queuing",
                  "ncsa":"National Center for Supercomputing Applications",
                  "ndps":"Novell Distributed Print Services",
                  "nds":"Novell Directory Services",
                  "nep":"Network Equipment Provider",
                  "netbios":"Network Basic Input/Output System",
                  "next":"Near-End CrossTalk",
                  "nfa":"Nondeterministic Finite Automaton",
                  "nfc":"Near field communication",
                  "nfs":"Network File System",
                  "ngl":"aNGeL",
                  "ngscb":"Next-Generation Secure Computing Base",
                  "ni":"National Instruments",
                  "nic":"Network Interface Controller",
                  "nim":"No Internal Message",
                  "nio":"New I/O",
                  "nist":"National Institute of Standards and Technology",
                  "nlp":"Natural Language Processing",
                  "nls":"Native Language Support",
                  "nmi":"Non-Maskable Interrupt",
                  "np":"Nondeterministic Polynomial time",
                  "npl":"Netscape Public License",
                  "npu":"Network Processing Unit",
                  "ns":"Netscape",
                  "nsa":"National Security Agency",
                  "nspr":"Netscape Portable Runtime",
                  "nntp":"Network News Transfer Protocol",
                  "noc":"Network Operations Center",
                  "nop":"No OPeration",
                  "nos":"Network Operating System",
                  "nptl":"Native POSIX Thread Library",
                  "nss":"Novell Storage Service",
                  "nss":"Network Security Services",
                  "nss":"Name Service Switch",
                  "nt":"New Technology",
                  "ntfs":"NT Filesystem",
                  "ntlm":"NT Lan Manager",
                  "ntp":"Network Time Protocol",
                  "numa":"Non-Uniform Memory Access",
                  "nurbs":"Non-Uniform Rational B-Spline",
                  "nvr":"Network Video Recorder",
                  "nvram":"Non-Volatile Random Access Memory",
                  "oasis":"Organization for the Advancement of Structured Information Standards",
                  "oat":"Operational Acceptance Testing",
                  "obsai":"Open Base Station Architecture Initiative",
                  "odbc":"Open Database Connectivity",
                  "oem":"Original Equipment Manufacturer",
                  "oes":"Open Enterprise Server",
                  "oftc":"Open and Free Technology Community",
                  "oid":"Object Identifier",
                  "olap":"Online Analytical Processing",
                  "ole":"Object Linking and Embedding",
                  "oled":"Organic Light Emitting Diode",
                  "olpc":"One Laptop per Child",
                  "oltp":"Online Transaction Processing",
                  "omf":"Object Module Format",
                  "omg":"Object Management Group",
                  "omr":"Optical Mark Reader",
                  "oo":"Object-Oriented",
                  "oo":"OpenOffice",
                  "ooe":"Out-of-Order Execution",
                  "oom":"Out Of Memory",
                  "ooo":"OpenOffice.org",
                  "oooe":"Out-of-Order Execution",
                  "oop":"Object-Oriented Programming",
                  "ootb":"Out of the box",
                  "opml":"Outline Processor Markup Language",
                  "orb":"Object Request Broker",
                  "orm":"Object-Relational Mapping",
                  "os":"Open Source",
                  "os":"Operating System",
                  "oscon":"O'Reilly Open Source CONvention",
                  "osdn":"Open Source Developer Network",
                  "osi":"Open Source Initiative",
                  "osi":"Open Systems Interconnection",
                  "ospf":"Open Shortest Path First",
                  "oss":"Open Sound System",
                  "oss":"Open-Source Software",
                  "oss":"Operations Support System",
                  "ostg":"Open Source Technology Group",
                  "oui":"Organisationally Unique Identifier",
                  "p2p":"Peer-To-Peer",
                  "paas":"Platform as a Service",
                  "pan":"Personal Area Network",
                  "pap":"Password Authentication Protocol",
                  "parc":"Palo Alto Research Center",
                  "pata":"Parallel ATA",
                  "pbs":"Portable Batch System",
                  "pc":"Personal Computer",
                  "pcb":"Printed Circuit Board",
                  "pcb":"Process Control Block",
                  "pc dos":"Personal Computer Disc Operating System",
                  "pci":"Peripheral Component Interconnect",
                  "pcie":"PCI Express",
                  "pcl":"Printer Command Language",
                  "pcmcia":"Personal Computer Memory Card International Association",
                  "pcm":"Pulse-Code Modulation",
                  "pcre":"Perl Compatible Regular Expressions",
                  "pd":"Public Domain",
                  "pda":"Personal Digital Assistant",
                  "pdf":"Portable Document Format",
                  "pdh":"Plesiochronous Digital Hierarchy",
                  "pdp":"Programmed Data Processor",
                  "pe":"Physical Extents",
                  "perl":"Practical Extraction and Reporting Language",
                  "pfa":"Please Find Attachment",
                  "pga":"Pin Grid Array",
                  "pga":"Programmable Gate Array",
                  "pgo":"Profile-Guided Optimization",
                  "pgp":"Pretty Good Privacy",
                  "php":"Hypertext Preprocessor",
                  "pic":"Peripheral Interface Controller",
                  "pic":"Programmable Interrupt Controller",
                  "pid":"Proportional-Integral-Derivative",
                  "pid":"Process ID",
                  "pim":"Personal Information Manager",
                  "pine":"Program for Internet News and Email",
                  "pim":"Platform Independent Model",
                  "pio":"Programmed Input/Output",
                  "pkcs":"Public Key Cryptography Standards",
                  "pki":"Public Key Infrastructure",
                  "plc":"Power Line Communication",
                  "plc":"Programmable Logic Controller",
                  "pld":"Programmable Logic Device",
                  "pl/i":"Programming Language One",
                  "pl/m":"Programming Language for Microcomputers",
                  "pl/p":"Programming Language for Prime",
                  "plt":"Power Line Telecommunications",
                  "pmm":"POST Memory Manager",
                  "png":"Portable Network Graphics",
                  "pnp":"Plug-and-Play",
                  "poe":"Power over Ethernet",
                  "poid":"Persistent Object Identifier",
                  "pojo":"Plain Old Java Object",
                  "pop":"Point of Presence",
                  "pop3":"Post Office Protocol v3",
                  "posix":"Portable Operating System Interface",
                  "post":"Power-On Self Test",
                  "ppc":"PowerPC",
                  "ppi":"Pixels Per Inch",
                  "ppp":"Point-to-Point Protocol",
                  "pppoa":"PPP over ATM",
                  "pppoe":"PPP over Ethernet",
                  "pptp":"Point-to-Point Tunneling Protocol",
                  "pr-pull request":"",
                  "ps":"PostScript",
                  "ps/2":"Personal System/2",
                  "psa":"Professional Services Automation",
                  "psm":"Platform Specific Model",
                  "psu":"Power Supply Unit",
                  "psvi":"Post-Schema-Validation Infoset",
                  "pts-dos":"PhysTechSoft - Disk Operating System",
                  "pv":"Physical Volume",
                  "pvg":"Physical Volume Group",
                  "pvr":"Personal Video Recorder",
                  "pxe":"Preboot Execution Environment",
                  "pxi":"PCI eXtensions for Instrumentation",
                  "qdr":"Quad Data Rate",
                  "qa":"Quality Assurance",
                  "qfp":"Quad Flat Package",
                  "qos":"Quality of Service",
                  "qotd":"Quote of the Day",
                  "qt":"Quasar Toolkit",
                  "qtam":"Queued Teleprocessing Access Method",
                  "qsop":"Quarter Small Outline Package",
                  "racf":"Resource Access Control Facility",
                  "rad":"Rapid Application Development",
                  "radius":"Remote Authentication Dial In User Service",
                  "raid":"Redundant Array of Independent Disks",
                  "raid":"Redundant Array of Inexpensive Disks",
                  "raii":"Resource Acquisition Is Initialization",
                  "rait":"Redundant Array of Inexpensive Tapes",
                  "ram":"Random Access Memory",
                  "rarp":"Reverse Address Resolution Protocol",
                  "ras":"Reliability",
                  "ras":"Remote Access Service",
                  "rras":"Routing and Remote Access Service",
                  "rc":"Region Code",
                  "rc":"Release Candidate",
                  "rc":"Run Commands",
                  "rcs":"Revision Control System",
                  "rdbms":"Relational Database Management System",
                  "rdc":"Remote Desktop Connection",
                  "rdf":"Resource Description Framework",
                  "rdm":"Relational Data Model",
                  "rdos":"Real-time Disk Operating System",
                  "rds":"Remote Data Services",
                  "refal":"Recursive Functions Algorithmic Language",
                  "rest":"Representational State Transfer",
                  "regex":"Regular Expression",
                  "regexp":"Regular Expression",
                  "rf":"Radio Frequency",
                  "rfc":"Request For Comments",
                  "rfi":"Radio Frequency Interference",
                  "rfid":"Radio Frequency Identification",
                  "rgb":"Red",
                  "rgba":"Red",
                  "rhl":"Red Hat Linux",
                  "rhel":"Red Hat Enterprise Linux",
                  "ria":"Rich Internet Application",
                  "riaa":"Recording Industry Association of America",
                  "rip":"Raster Image Processor",
                  "rip":"Routing Information Protocol",
                  "rir":"Regional Internet registry",
                  "risc":"Reduced Instruction Set Computer",
                  "risc os":"Reduced Instruction Set Computer Operating System",
                  "rje":"Remote Job Entry",
                  "rle":"Run-Length Encoding",
                  "rll":"Run-Length Limited",
                  "rmi":"Remote Method Invocation",
                  "rms":"Richard Matthew Stallman",
                  "rom":"Read Only Memory",
                  "romb":"Read-Out Motherboard",
                  "rom-dos":"Read Only Memory - Disk Operating System",
                  "rpc":"Remote Procedure Call",
                  "rpg":"Report Program Generator",
                  "rpm":"RPM Package Manager",
                  "rsa":"Rivest Shamir Adleman",
                  "rsi":"Repetitive Strain Injury",
                  "rss":"Radio Service Software",
                  "rss":"Rich Site Summary",
                  "rtai":"Real-Time Application Interface",
                  "rtc":"Real-Time Clock",
                  "rte":"Real-Time Enterprise",
                  "rtems":"Real-Time Executive for Multiprocessor Systems",
                  "rtl":"Right-to-Left",
                  "rtos":"Real-Time Operating System",
                  "rtp":"Real-time Transport Protocol",
                  "rts":"Ready To Send",
                  "rtsp":"Real Time Streaming Protocol",
                  "rtti":"Run-time Type Information",
                  "rwd":"Responsive Web Design",
                  "saas":"Software as a Service",
                  "san":"Storage Area Network",
                  "sas":"Serial attached SCSI",
                  "sata":"Serial ATA",
                  "sax":"Simple API for XML",
                  "sbod":"Spinning Beachball of Death",
                  "sbp-2":"Serial Bus Protocol 2",
                  "sbin":"superuser binary",
                  "sbu":"Standard Build Unit",
                  "scada":"Supervisory Control And Data Acquisition",
                  "scid":"Source Code in Database",
                  "scm":"Software Configuration Management",
                  "scm":"Source Code Management",
                  "scp":"Secure Copy",
                  "scpi":"Standard Commands for Programmable Instrumentation",
                  "scsaâ€“secure content storage association":"",
                  "scsi":"Small Computer System Interface",
                  "sctp":"Stream Control Transmission Protocol",
                  "sd":"Secure Digital",
                  "sddl":"Security Descriptor Definition Language",
                  "sdh":"Synchronous Digital Hierarchy",
                  "sdi":"Single Document Interface",
                  "sec":"Single Edge Contact",
                  "sdio":"Secure Digital Input Output",
                  "sdk":"Software Development Kit",
                  "sdl":"Simple DirectMedia Layer",
                  "sdn":"Service Delivery Network",
                  "sdp":"Session Description Protocol",
                  "sdr":"Software-Defined Radio",
                  "sdram":"Synchronous Dynamic Random Access Memory",
                  "sdsl":"Symmetric DSL",
                  "se":"Single Ended",
                  "sei":"Software Engineering Institute",
                  "seo":"Search Engine Optimization",
                  "sftp":"Secure FTP",
                  "sftp":"Simple File Transfer Protocol",
                  "sftp":"SSH File Transfer Protocol",
                  "sgi":"Silicon Graphics",
                  "sgml":"Standard Generalized Markup Language",
                  "sgr":"Select Graphic Rendition",
                  "sha":"Secure Hash Algorithm",
                  "shdsl":"Single-pair High-speed Digital Subscriber Line",
                  "sigcat":"Special Interest Group on CD-ROM Applications and Technology",
                  "siggraph":"Special Interest Group on Graphics",
                  "simd":"Single Instruction",
                  "simm":"Single Inline Memory Module",
                  "sip":"Session Initiation Protocol",
                  "sip":"Supplementary Ideographic Plane",
                  "sisd":"Single Instruction",
                  "siso":"Single-Input and Single-Output",
                  "sled":"SUSE Linux Enterprise Desktop",
                  "sles":"SUSE Linux Enterprise Server",
                  "sli":"Scalable Link Interface",
                  "slip":"Serial Line Internet Protocol",
                  "slm":"Service Level Management",
                  "sloc":"Source Lines of Code",
                  "sme":"Subject Matter Expert",
                  "spm":"Software project management",
                  "spmd":"Single Program",
                  "sma":"SubMiniature version A",
                  "smb":"Server Message Block",
                  "smbios":"System Management BIOS",
                  "smil":"Synchronized Multimedia Integration Language",
                  "s/mime":"Secure/Multipurpose Internet Mail Extensions",
                  "smp":"Supplementary Multilingual Plane",
                  "smp":"Symmetric Multi-Processing",
                  "sms":"Short Message Service",
                  "sms":"System Management Server",
                  "smt":"Simultaneous Multithreading",
                  "smtp":"Simple Mail Transfer Protocol",
                  "sna":"Systems Network Architecture",
                  "snmp":"Simple Network Management Protocol",
                  "sntp":"Simple Network Time Protocol",
                  "soa":"Service-Oriented Architecture",
                  "soap":"Simple Object Access Protocol",
                  "soap":"Symbolic Optimal Assembly Program",
                  "sopa":"Stop Online Piracy Act",
                  "soc":"System-on-a-Chip",
                  "so-dimm":"Small Outline DIMM",
                  "soe":"Standard Operating Environment",
                  "soho":"Small Office/Home Office",
                  "soi":"Silicon On Insulator",
                  "sp":"Service Pack",
                  "spa":"Single Page Application",
                  "spf":"Sender Policy Framework",
                  "spi":"Serial Peripheral Interface",
                  "spi":"Stateful Packet Inspection",
                  "sparc":"Scalable Processor Architecture",
                  "sql":"Structured Query Language",
                  "sram":"Static Random Access Memory",
                  "ssa":"Static Single Assignment",
                  "ssd":"Software Specification Document",
                  "ssd":"Solid-State Drive",
                  "sse":"Streaming SIMD Extensions",
                  "ssh":"Secure Shell",
                  "ssi":"Server Side Includes",
                  "ssi":"Single-System Image",
                  "ssi":"Small-Scale Integration",
                  "ssid":"Service Set Identifier",
                  "ssl":"Secure Socket Layer",
                  "ssp":"Supplementary Special-purpose Plane",
                  "ssse":"Supplementary Streaming SIMD Extensions",
                  "su":"superuser",
                  "sus":"Single UNIX Specification",
                  "suse":"Software und System-Entwicklung",
                  "svc":"Scalable Video Coding",
                  "svg":"Scalable Vector Graphics",
                  "svga":"Super Video Graphics Array",
                  "svd":"Structured VLSI Design",
                  "swf":"Shock Wave Flash",
                  "swt":"Standard Widget Toolkit",
                  "sysop":"System operator",
                  "tao":"Track-At-Once",
                  "tasm":"Turbo ASseMbler",
                  "tb":"TeraByte",
                  "tcl":"Tool Command Language",
                  "tcp":"Transmission Control Protocol",
                  "tcp/ip":"Transmission Control Protocol/Internet Protocol",
                  "tcu":"Telecommunication Control Unit",
                  "tdma":"Time Division Multiple Access",
                  "tft":"Thin Film Transistor",
                  "tftp":"Trivial File Transfer Protocol",
                  "ti":"Texas Instruments",
                  "tla":"Three-Letter Acronym",
                  "tld":"Top-Level Domain",
                  "tls":"Thread-Local Storage",
                  "tls":"Transport Layer Security",
                  "tlv":"Type-length-value",
                  "tmp":"temporary",
                  "tnc":"Terminal Node Controller",
                  "tnc":"Threaded Neill-Concelman connector",
                  "tpf":"Transaction Processing Facility",
                  "troff":"Trace Off",
                  "tron":"Trace On",
                  "tron":"The Real-time Operating system Nucleus",
                  "trs-dos":"Tandy Radio Shack - Disk Operating System",
                  "tso":"Time Sharing Option",
                  "tsp":"Traveling Salesman Problem",
                  "tsr":"Terminate and Stay Resident",
                  "tta":"True Tap Audio",
                  "ttf":"TrueType Font",
                  "ttl":"Transistor-Transistor Logic",
                  "ttl":"Time To Live",
                  "tts":"Text-to-Speech",
                  "tty":"Teletype",
                  "tucows":"The Ultimate Collection of Winsock Software",
                  "tug":"TeX Users Group",
                  "twain":"Technology Without An Interesting Name",
                  "uaag":"User Agent Accessibility Guidelines",
                  "uac":"User Account Control",
                  "uart":"Universal Asynchronous Receiver/Transmitter",
                  "uat":"User Acceptance Testing",
                  "ucs":"Universal Character Set",
                  "uddi":"Universal Description",
                  "udma":"Ultra DMA",
                  "udp":"User Datagram Protocol",
                  "uefi":"Unified Extensible Firmware Interface",
                  "uhf":"Ultra High Frequency",
                  "ui":"User Interface",
                  "ul":"Upload",
                  "ula":"Uncommitted Logic Array",
                  "uma":"Upper Memory Area",
                  "umb":"Upper Memory Block",
                  "uml":"Unified Modeling Language",
                  "uml":"User-Mode Linux",
                  "umpc":"Ultra-Mobile Personal Computer",
                  "unc":"Universal Naming Convention",
                  "ups":"Uninterruptible Power Supply",
                  "uri":"Uniform Resource Identifier",
                  "url":"Uniform Resource Locator",
                  "urn":"Uniform Resource Name",
                  "usb":"Universal Serial Bus",
                  "usr":"user",
                  "usr":"U.S. Robotics",
                  "utc":"Coordinated Universal Time",
                  "utf":"Unicode Transformation Format",
                  "utp":"Unshielded Twisted Pair",
                  "uucp":"Unix to Unix Copy",
                  "uuid":"Universally Unique Identifier",
                  "uun":"Universal User Name",
                  "uvc":"Universal Virtual Computer",
                  "ux":"User Experience",
                  "var":"variable",
                  "vax":"Virtual Address eXtension",
                  "vcpi":"Virtual Control Program Interface",
                  "vr":"Virtual Reality",
                  "vrml":"Virtual Reality Modeling Language",
                  "vb":"Visual Basic",
                  "vba":"Visual Basic for Applications",
                  "vbs":"Visual Basic Script",
                  "vdsl":"Very High Bitrate Digital Subscriber Line",
                  "vesa":"Video Electronics Standards Association",
                  "vfat":"Virtual FAT",
                  "vfs":"Virtual File System",
                  "vg":"Volume Group",
                  "vga":"Video Graphics Array",
                  "vga":"Video Graphics Adapter",
                  "vhf":"Very High Frequency",
                  "vlan":"Virtual Local Area Network",
                  "vlsm":"Variable Length Subnet Mask",
                  "vlb":"Vesa Local Bus",
                  "vlf":"Very Low Frequency",
                  "vliw":"Very Long Instruction Word",
                  "vlsi":"Very-Large-Scale Integration",
                  "vm":"Virtual Machine",
                  "vm":"Virtual Memory",
                  "vnc":"Virtual Network Computing",
                  "vod":"Video On Demand",
                  "voip":"Voice over Internet Protocol",
                  "vpn":"Virtual Private Network",
                  "vpu":"Visual Processing Unit",
                  "vsam":"Virtual Storage Access Method",
                  "vsat":"Very Small Aperture Terminal",
                  "vt":"Video Terminal?",
                  "vtam":"Virtual Telecommunications Access Method",
                  "w3c":"World Wide Web Consortium",
                  "wwdc":"Apple World Wide Developer Conference",
                  "wafs":"Wide Area File Services",
                  "wai":"Web Accessibility Initiative",
                  "wais":"Wide Area Information Server",
                  "wan":"Wide Area Network",
                  "wap":"Wireless Access Point",
                  "wap":"Wireless Application Protocol",
                  "wasm":"Watcom ASseMbler",
                  "wbem":"Web-Based Enterprise Management",
                  "wcag":"Web Content Accessibility Guidelines",
                  "wcf":"Windows Communication Foundation",
                  "wdm":"Wavelength-Division Multiplexing",
                  "webdav":"WWW Distributed Authoring and Versioning",
                  "wep":"Wired Equivalent Privacy",
                  "wfi":"Wait For Interrupt",
                  "wimax":"Worldwide Interoperability for Microwave Access",
                  "winfs":"Windows Future Storage",
                  "wins":"Windows Internet Name Service",
                  "wlan":"Wireless Local Area Network",
                  "wma":"Windows Media Audio",
                  "wmv":"Windows Media Video",
                  "wol":"Wake-on-LAN",
                  "wor":"Wake-on-Ring",
                  "wora":"Write once",
                  "wore":"Write once",
                  "wpa":"Wi-Fi Protected Access",
                  "wpan":"Wireless Personal Area Network",
                  "wpf":"Windows Presentation Foundation",
                  "wsdl":"Web Services Description Language",
                  "wsfl":"Web Services Flow Language",
                  "wusb":"Wireless Universal Serial Bus",
                  "wwan":"Wireless Wide Area Network",
                  "wwid":"World Wide Identifier",
                  "wwn":"World Wide Name",
                  "www":"World Wide Web",
                  "wysiwyg":"What You See Is What You Get",
                  "wzc":"Wireless Zero Configuration",
                  "xag":"XML Accessibility Guidelines",
                  "xaml":"eXtensible Application Markup Language",
                  "xdm":"X Window Display Manager",
                  "xdmcp":"X Display Manager Control Protocol",
                  "xcbl":"XML Common Business Library",
                  "xhtml":"eXtensible Hypertext Markup Language",
                  "xilp":"X Interactive ListProc",
                  "xml":"eXtensible Markup Language",
                  "xmms":"X Multimedia System",
                  "xmpp":"eXtensible Messaging and Presence Protocol",
                  "xms":"Extended Memory Specification",
                  "xns":"Xerox Network Systems",
                  "xp":"Cross-Platform",
                  "xp":"Extreme Programming",
                  "xpcom":"Cross Platform Component Object Model",
                  "xpi":"XPInstall",
                  "xpidl":"Cross-Platform IDL",
                  "xps":" XML Paper Specification",
                  "xsd":"XML Schema Definition",
                  "xsl":"eXtensible Stylesheet Language",
                  "xsl-fo":"eXtensible Stylesheet Language Formatting Objects",
                  "xslt":"eXtensible Stylesheet Language Transformations",
                  "xss":"Cross-Site Scripting",
                  "xtf":"eXtensible Tag Framework",
                  "xtf":"eXtended Triton Format",
                  "xul":"XML User Interface Language",
                  "xvga":"Extended Video Graphics Adapter",
                  "y2k":"Year Two Thousand",
                  "yaaf":"Yet Another Application Framework",
                  "yacc":"Yet Another Compiler Compiler",
                  "yaml":"YAML Ain't Markup Language",
                  "yast":"Yet another Setup Tool",
                  "zcav":"Zone Constant Angular Velocity",
                  "zcs":"Zero Code Suppression",
                  "zif":"Zero Insertion Force",
                  "zifs":"Zero Insertion Force Socket",
                  "zisc":"Zero Instruction Set Computer",
                  "zoi":"Zero One Infinity",
                  "zope":"Z Object Publishing Environment",
                  "zma":"Zone Multicast Address",
                  "zpl":"Z-level Programming Language",
});

exports.words = words