'use strict';

var React = require('react-native');
var Immutable = require('immutable');

var words = Immutable.Map({
                  "aal":"ATM Adapter LayerATM适配",
                  "abc":"Automatic Brightness Control自动亮度控",
                  "acm":"Association for Computing Machinery美国计算机协",
                  "adc":"Analog-to-Digital Convener模数转换",
                  "ado":"ActiveX Data Objects动态数据对",
                  "adp":"Automatic Data Processing自动数据处",
                  "adpcm":"Adaptive Digital Pulse Code Modulation自适应数字脉冲编码调",
                  "adsl":"Asymmetrical Digital Subscriber Loop非对称数字用户环",
                  "agp":"Accelerated Graphics Port加速图形端",
                  "ai":"Artificial Intelligence人工智",
                  "ansi":"American National Standard Institute美国国家标准协",
                  "aol":"American On Line美国在",
                  "api":"Application Program Interface应用程序接",
                  "apm":"Advanced Power Management高级电源管",
                  "arc":"Augmentation Research Center 扩大研究中",
                  "arp":"Address Resolution Protocol地址解析协议",
                  "arpa":"Advanced Research Project Agency远景研究规划",
                  "arq":"Automatic Repeat Request自动重复请",
                  "ascii":"American Standard Code for Information Interchange美国信息交换标准代",
                  "atm":"Asynchronous Transfer Mode异步传输模",
                  "avi":"Audio Video Interleaved一种Windows的多媒体文件格",
                  "awt":"Abstract Windows Toolkit抽象窗口工具",
                  "b5":"Big-5大五(码",
                  "basic":"Beginner's All-purpose Symbolic Instruction Code初学者的通用符号指令码(基础语言",
                  "bbs":"Bulletin Board System(电子)公告板系",
                  "bcc":"Blind Courtesy Copy(电子邮件)盲式副",
                  "bft":"Binary File Transfer二进制文件传",
                  "b-isdn":"Broadband ISDN宽带ISDN",
                  "bisync":"Binary Synchronous Communications Protocol二进制同步通信协",
                  "bmp":"Bitmap位",
                  "bof":"Birds Of Feather专题讨论小",
                  "bps":"bits per second位每",
                  "bri":"Basic Rate Interface基本速率接口",
                  "bsc":"Binary Synchronization Communication二进制同步通信规程",
                  "c/s":"Client/Server客户机/服务",
                  "ca":"Certificate Authority证书机",
                  "cad":"Computer Aided Design计算机辅助设",
                  "cai":"Computer Aided Instruction计算机辅助教",
                  "cam":"Computer Aided Manufacturing计算机辅助制",
                  "case":"Computer Aided Software Engineering计算机辅助软件工",
                  "cat":"Computer Aided Testing计算机辅助测",
                  "cbt":"Computer-Based Training基于计算机的训",
                  "cc":"Courtesy Copy(电子邮件)副",
                  "cccii":"Chinese Character Code for Information Interchange汉字信息交换",
                  "ccitt":"Consultative Committee for International Telegraph and Telephone国际电报电话咨询委员",
                  "cd":"Carrier Detect载波侦",
                  "cd":"Compact Disc光",
                  "cddi":"Copper Distributed Data Interface铜线分布式数据接",
                  "cd-e":"Compact Disc-Erasable可擦除光",
                  "cd-i":"Compact Disc-Interactive互动式光",
                  "cd-r":"Compact Disc-Recordable可录光",
                  "cd-rom":"Compact Disc-Read Only Memory只读光",
                  "cd-rw":"Compact Disc-Rewritable可重写光",
                  "cern":"European Laboratory for Particle Physics欧洲粒子物理实验",
                  "cernet":"China Education and Research Network中国教育科研",
                  "cert":"Computer Emergency Response Team计算机紧急情况反应小",
                  "cgi":"Common Gateway Interface通用网关界",
                  "cgi":"Computer Graphic Interface计算机图形接",
                  "china ddn":" 中国公用数字数据",
                  "china pac":" 中国公用数据",
                  "cim":"CompuServe Information Manager一种CompuServe的图形界面程",
                  "cim":"Computer Input Microfilm计算机输入缩微胶",
                  "cisc":"Complex Instruction Set Computer复杂指令集计算",
                  "cix":"Commercial Internet Exchange商务因特网交换中心(连接点",
                  "cmi":"Computer Managed Instruction计算机管理教",
                  "cmos":"Complementary Metal Oxide Semiconductor互补金属氧化物半导",
                  "cmyk":"Cyan Magenta Yellow Black青色、洋红、黄色、黑",
                  "co/dec":"Coding and Decoding编码/解",
                  "coa":"Certificate Of Authenticity真品证",
                  "com":"Component Object Model组建对象模",
                  "cps":"characters per second字符每秒",
                  "cpu":"Central Processing Unit中央处理",
                  "crc":"Cyclical Redundancy Check循环冗余检",
                  "cren":"Corporation for Research and Educational Networking 研究与教学连网组",
                  "cs":"Convergence Sub layer传输会聚子",
                  "cscw":"Computer Supported Cooperative Work 计算机支持的协同工",
                  "csma/cd":"Carrier Sense Multiple Access with Collision Detection载波侦听多址访问/冲突检",
                  "csnet":"Community Service Network社区服务网",
                  "csnet":"Computer and Science Network计算机与科学网",
                  "cso":"Computing Services Office计算机服务机",
                  "css":"Cascading Style Sheets级联样式",
                  "cti":"Computer Telephony Integration计算机电话集",
                  "cts":"Clear To Send清除发",
                  "dac":"Digital-to-Analog Convener数模转换",
                  "darpa":"Define Advanced Research Projects Agency of the Department of Defense(美国)国防高级研究计划",
                  "db":"Database数据",
                  "dce":"Data Communication Equipment数据通信设",
                  "dde":"Dynamic Data Exchange动态数据交",
                  "ddn":"Digital Data Network数字数据网",
                  "den":"Directory Enabled Network目录驱动网",
                  "des":"Data Encryption Standard数据加密标",
                  "dhcp":"Dynamic Host Configuration Protocol动态主机配置协",
                  "dhtml":"Dynamic Hyper Text Makeup Language动态超文本标记语",
                  "dimm":"Double In-Line Memory Module(168线内存插槽",
                  "dis":"Distributed Interactive Simulation分布式交互仿",
                  "dix":" 数据链路层和物理层规范也称DIX规",
                  "diy":"Do It Yourself自己动",
                  "dl":"Data Link数据链",
                  "dll":"Dynamic Link Library动态链接",
                  "dma":"Direct Memory Access直接存储器存",
                  "dmi":"Desktop Management Interface桌面管理界",
                  "dnic":"Data Netwrok Indentifier Code数据网络识别码",
                  "dns":"Domain Naming System域名系统",
                  "dns":"Digital Nervous System数字神经系",
                  "dns":"Domain Name Server域名服务",
                  "dns":"Domain Name System域名系",
                  "dom":"Document Object Model文档对象模",
                  "dos":"Disk Operating System磁盘操作系",
                  "dpi":"dots per inch点每英",
                  "dram":"Dynamic Random Access Memory 动态随机存取存储",
                  "dsl":"Data Set Label数据集标",
                  "dsl":"Digital Subscriber Line数字用户线",
                  "dsp":"Digital Signal Processing数字信号处",
                  "dsp":"Digital Signal Processor数字信号处理",
                  "dsr":"Data Set Ready数据准备就",
                  "dtd":"Document Type Definition文档类型定",
                  "dte":"Data Terminal Equipment数据终端设",
                  "dtr":"Data Terminal Ready数据终端就",
                  "du":"Data Unit数据单元",
                  "dvd":"Digital Video Disc数字影像光",
                  "dvr":"Distributed Virtual Reality分布式虚拟现",
                  "dxi":"Data Exchange Interface数据交换接",
                  "e1":" 支持32路PCM载波信号的欧洲PCM载波标",
                  "eacc":"East Asian Character Code东亚字",
                  "ecc":"Error Checking and Correcting错误侦测校",
                  "ecp":"Extended Capabilities Port扩展端",
                  "ecpa":"Electronic Communications Privacy Act电子通信保密",
                  "edi":"Electronic Data Interchange电子数据交",
                  "edo":"Extended Data Out扩展数据输",
                  "edp":"Electronic Data Processing电子数据处",
                  "ega":"Enhanced Graphic Adapter增强图像适配",
                  "eia":"Electronic Industries Association电子工业协",
                  "eide":"Enhanced Integrated Devices Electronics增强型综合电器界",
                  "eisa":"Enhanced Industry Standard Architecture增强型工业标准结",
                  "e-mail":"Electronic-mail电子邮",
                  "ems":"Extended Memory Specification扩展内存规",
                  "eot":"End Of Transmission传输结",
                  "epp":"Enhanced Parallel Port增强型并行端",
                  "eprom":"Erasable Programmable Read Only Memory可擦可编程只读存储",
                  "esd":"Electronic Software Distribution电子软件分",
                  "esdi":"Enhanced Small Device Interface增强小型设备接",
                  "faq":"Frequently Asked Question常见问",
                  "faql":"Frequently Ask Question List常见问题列",
                  "fat":"File Allocation Table文件分配",
                  "fd":"Floppy Disk软",
                  "fd":"Full Duplex全双",
                  "fdc":"Floppy Disk Connector软盘连接",
                  "fdd":"Floppy Disk Drive软盘驱动",
                  "fddi":"Fiber Distributed Data Interface光纤分布数据接",
                  "fdm":"Frequency Division Multiplexing频分多路复",
                  "fpe":"Fix People Expert整人专家(软件",
                  "fpm":"Fast Page Mode快速页模",
                  "fr":"Frame Relay帧中",
                  "fsb":"Front-Side Bus前端总",
                  "ftam":"File Transfer Access and Management文件传输访问与管",
                  "ftp":"File Transfer Protocol文件传送协",
                  "fyi":"For Your Information用户信",
                  "gb":"GigaBit千兆",
                  "gb":"GigaByte 千兆字",
                  "gb":"Guo Biao 国",
                  "gbk":"Guo Biao Kuozhan国标扩展(码",
                  "gdi":"Graphic Device Interface图形设备接",
                  "gif":"Graphic Interchange Format图型交换格",
                  "gip":"Global Internet Project全球因特网计划(联盟",
                  "gml":"Generalized Markup Language通用标记语",
                  "gps":"Global Positioning System全球定位系",
                  "gsm":"Global Standard for Mobile Communication全球移动通信系",
                  "gui":"Graphic User Interface图形用户界",
                  "hd":"Half Duplex半双",
                  "hd":"High Density高",
                  "hd":"Hard Disk硬",
                  "hdc":"Hard Disk Connector硬盘连接",
                  "hdd":"Hard Disk Drive硬盘驱动",
                  "hdlc":"High-level Data Link Control高级数据链路控",
                  "hdtv":"High Density Television高密度电",
                  "hex":"Hexadecimal十六进",
                  "hga":"Hercules Graphic Adapter大力士显示适配",
                  "hpc":"Handheld Personal Computer手持个人电",
                  "hppi":"High Performance Parallel Interface高性能并行接",
                  "html":"Hyper Text Makeup Language超文本标记语",
                  "http":"Hypertext Transfer Protocol超文本传输协",
                  "http-ng":"Hyper Text Transfer Protocol-Next Generation下一代超文本传送协",
                  "hub":" 集线",
                  "hz":"Hertz赫",
                  "ibm":"International Business Machines国际商业机器(公司",
                  "ic":"Integrated Circuit集成电",
                  "icmp":"Internet Control Message Protocol因特网控制消息协",
                  "icp":"Internet Content Provider因特网内容提供",
                  "icq":"I Seek You 网上寻",
                  "ide":"Integrated Devices Electronics综合电器界",
                  "idf":"Intel Developer Forum英特尔开发者论",
                  "idg":"International Data Group国际数据组",
                  "idsl":"Internet Digital Subscriber Line因特网数字用户线",
                  "idu":"Interface Data Unit接口数据单",
                  "ie":"Internet Explorer(微软)因特网浏览",
                  "ieee":"Institute of Electrical and Electronic Engineers电机及电子工程师协",
                  "iff":"Interchange File Format文件交换格",
                  "iis":"Internet Information Server因特网信息服务",
                  "ip":"Internet Protocol(因特网)网间通信协",
                  "ipc":"Industrial PC工业控制微",
                  "ipx":"Internet work Packet exchange因特网络分组交",
                  "irc":"Internet Relay Chat网上实时聊",
                  "irq":"Interrupt Request (Line)中断请求(线路",
                  "isa":"Industry Standard Architecture工业标准体系结构(AT总线",
                  "isdn":"Integrated Services Digital Network综合业务数字",
                  "ism":"Internet Server Manager因特网服务管理",
                  "iso":"International Standardization Organization国际标准化组",
                  "isoc":"Internet Society因特网协",
                  "isp":"Internet Service Provider因特网服务提供",
                  "isv":"Independent Software Vendor独立软件供应",
                  "it":"Information Technology信息技",
                  "jdk":"Java Development KitJava语言开发工具",
                  "jpeg":"Joint Photographic Experts Group联合照相专家",
                  "jvm":"Java Virtual MachineJava虚拟",
                  "kb":"Kilobyte千字",
                  "kbps":"Kilobits per second千位每",
                  "kdd":"Knowledge Discovery in Database数据库中的知识发",
                  "lan":"Local Area Network局域",
                  "lane":"Local Area Network Emulation局域网仿",
                  "lap-m":"Link Access Procedure for Modems调制解调器连接访问协",
                  "lc":"Logical Circuit逻辑链",
                  "lcd":"Liquid Crystal Display液晶显",
                  "ld":"Laser Disc激光",
                  "ldap":"Lightweight Directory Access Protocol简单的目录访问协",
                  "ldcm":"LANDesk Client Manager终端客户管理程",
                  "lec":"LAN Emulation Client局域网仿真客",
                  "les":"LAN Emulation Server局域网仿真服务",
                  "llc":"Logical Link Control逻辑链路控",
                  "lpi":"lines per inch行每英",
                  "lpt":"Line Print行式打印机(并行)端",
                  "mac":"Medium Access Control媒体访问控",
                  "man":"Metropolitan Area Network城域",
                  "mapi":"Messaging Application Programming Interface通信应用程序接",
                  "mau":"Multiple Access Unit多路访问",
                  "mb":"MegaByte兆字",
                  "mbone":"Multicast Backbone多播主干",
                  "mca":"Micro Channel Architecture微通道结",
                  "mcga":"MultiColor Graphics Array彩色图形阵",
                  "mci":"Media Control Interface媒体控制接",
                  "mda":"Monochrome Display Adapter单色显示适配",
                  "mdi":"Multiple Document Interface媒体相关接",
                  "midi":"Musical Instrument Digital Interface乐器数字化接",
                  "mime":"Multipurpose Internet Mail Extensions 多用途因特网邮件扩",
                  "mips":"Millions of Instructions Per Second百万词条指令每秒",
                  "mlp":"Multiple Link Protocol多链路规",
                  "mmm":"Mobile Media Mode移动媒体模",
                  "mmx":"Multimedia Xtension多媒体扩展指令",
                  "mo":"Magneto Optical (Disc)磁介质光",
                  "modem":"Modulator-Demodulator调制解调",
                  "motd":"Message Of The Day每日邮",
                  "motss":"Members Of The Same Sex同性别会",
                  "mpeg":"Motion Picture Expert Group动态影像压缩标",
                  "mpoa":"MultiProtocol Over ATMATM上的多协",
                  "mpr":" 瑞典国家计量和测试机构",
                  "ms":"Microsoft 微软(公司",
                  "msn":"Microsoft Network微软网",
                  "mtbf":"Mean Time Between Failures平均失效间隔时",
                  "mttr":"Mean Time To Repair平均修复时",
                  "mud":"Multiple Users Dialogue (Dungeons)多用户对话(泥巴网络地牢游戏",
                  "nak":"Negative Acknowledge否",
                  "nat":"Network Address Translation网址解",
                  "nc":"Network Computer网络计算",
                  "ncsa":"National Center for Supercomputing Applications(美国)国家超级计算应用中",
                  "nfs":"Network File System网络文件系",
                  "nic":"Network Information Center网络信息中",
                  "nic":"Network Interface Card网",
                  "n-isdn":"Narrowband ISDN窄带ISD",
                  "nmc":"Network Manager Center网络管理中",
                  "nms":"Network Management System网络管理系",
                  "nni":"Network-Network Interface网络/网络端接",
                  "nntp":"Network News Transport Protocol网络新闻传输协",
                  "noc":"Network Operations Center 网络操作中",
                  "nren":"National Research and Education Network 国家研究与教育",
                  "nrni":" 不归0交替编",
                  "nsf":"National Science Foundation国家科学基金",
                  "nt":"Network Terminal网络终",
                  "nt":"New Technology新技",
                  "ntfs":"NT File System(微软)NT文件系",
                  "ntlm":"NT LanMan WindowsNT挑战与响应验证协",
                  "ntsc":"National Television Standard Committee国家电视标准委员",
                  "oa":"Office Automation办公自动",
                  "ocr":"Optical Character Recognition光学扫描字符识",
                  "oct":"Octal八进",
                  "odb":"Output to Display Buffer显示输出缓",
                  "odbc":"Open Database Connectivity开放的数据库连",
                  "oem":"Original Equipment Manufacture初始设备制造",
                  "oh":"Off Hook(调制解调器)摘",
                  "olcr":"Online Character Recognition在线手写识",
                  "ole":"Object Linking and Embedding对象链接与嵌",
                  "oltp":"Online Transaction Processing联机事务处",
                  "one":"Open Network Environment开放网络环",
                  "opac":"Online Public Access Catalog在线公共检索目",
                  "os":"Operating System操作系",
                  "osd":"On Screen Display屏幕显示(菜单",
                  "osi":"Open System Interconnection开放系统互",
                  "osp":"Online Service Provider在线服务提供",
                  "pad":"Packet Assembler Disassemble包装、拆卸设",
                  "pap":"Password Authentication Protocol密码认证协",
                  "pc":"Personal Computer个人计算",
                  "pcb":"Printed Circuit Board印刷电路",
                  "pci":"Protocol Control Information协议控制信",
                  "pci":"Peripheral Component Interconnect外围设备互",
                  "pcm":"Pulse Code Modulation脉码调",
                  "pcmcia":"Personal Computer Memory Card International Association(个人计算机存储卡国际协会",
                  "pda":"Personal Digital Assistant个人数字助",
                  "pdf":"Portable Document Format可移植文档格",
                  "pdh":" 准同步数字体",
                  "pdu":"Protocol Data Unit协议数据单",
                  "perl":"Practical Extraction and Reporting Language 实际抽取报告语",
                  "pgp":"Pretty Good Privacy高度保",
                  "pics":"Platform for Internet Content Selection因特网内容检索平",
                  "pm":"Physical Medium物理媒体子",
                  "pnp":"Plug and Play即插即",
                  "pop":"Post Office Protocol邮局协",
                  "ppc":"Palm Personal Computer掌上个人电",
                  "ppm":"pages per minute页每分",
                  "ppp":"Point to Point Protocol点对点协",
                  "pptp":"Point to Point Tunneling Protocol点对点通道协",
                  "pri":"Primary Rate Interface一次群速率接口",
                  "prom":"Programmable Read Only Memory可编程只读存储",
                  "psdn":"Packet Switched Data Network分组交换数据",
                  "pse":"Packet Switched Equipment分组交换设",
                  "psn":"Packet Switching Network包交换网",
                  "psn":"Packet Switching Node包交换节",
                  "pstn":"Public Switched Telephone Network公用交换电话",
                  "pvc":"Permanent Virtual Circuit永久虚电",
                  "qos":"Quality of Service服务质",
                  "qtam":"Queued Telecommunications Access Method排队远程通信访问方",
                  "r&d":"Research and Development研究与发",
                  "raid":"Redundant Arrays of Inexpensive Disks磁盘冗余阵",
                  "ram":"Random Access Memory随机存储",
                  "rarp":"Reverse Address Resolution Protocol逆向地址解析协",
                  "rdbms":"Relational Database Management System关系数据库管理系",
                  "rdf":"Resource Description Framework资源描述结",
                  "rfc":"Request For Comments请求评议(文档",
                  "rgb":"Red Green Blue红绿",
                  "risc":"Reduced Instruction Set Computer精简指令集计算",
                  "rj":"Registered Jack标准插",
                  "rom":"Read Only Memory只读存储",
                  "rpg":"Roles Play Games角色扮演游",
                  "rpu":" 环中继转发",
                  "rts":"Request To Send发送请",
                  "sar":"Segmentation and Reassembly sub layer分段、组装子",
                  "scsi":"Small Computer System Interface小型计算机系统接",
                  "sdh":"Synchronous Digital Hierarchy同步数字体",
                  "sdk":"Software Development Kit软件开发工具",
                  "sdlc":"Synchronous Data Link Control同步数字体",
                  "sdram":"Synchronous Dynamic Random Access Memory同步动态随机存取存储器(同步内存",
                  "sdu":"Service Data Unit服务数据单",
                  "set":"Secure Electronic Transaction安全电子交",
                  "sgml":"Standard Generalized Makeup Language标准普及标识语",
                  "shttp":"Secure Hyper Text Transfer Protocol安全超文本传送协",
                  "simm":"Single In-Line Memory Module(72线内存插槽",
                  "slip":"Serial Line Internet Protocol串列线路网际协",
                  "slp":"Single Link Protocol单链路规",
                  "smds":"Switched Multimegabit Data Service多兆位数据交换业",
                  "smil":"Synchronize Multimedia Integration Language同步多媒体集成语",
                  "smp":"Symmetric Multiprocessing对称多任务处",
                  "smtp":"Simple Mail Transfer Protocol简单邮件传输协",
                  "smtp":"Simple Mail Transfer Protocol简单邮件传输协",
                  "sna":"Systems Network Architecture系统网络体系结",
                  "snmp":"Simple Network Management Protocol简单网络管理协",
                  "soho":"Small Office / Home Office小型/家庭办",
                  "sonet":"Synchronous Optical Network同步光纤",
                  "spp":"Standard Parallel Port 标准并行端",
                  "sql":"Structured Query Language结构化查询语",
                  "sram":"Static Random Access Memory静态随机存取存储",
                  "ssd":"Solid-State Disk固态",
                  "ssl":"Secure Sockets Layer安全套接",
                  "std":"Suspend to Disk悬挂于磁",
                  "stp":"Shielded Twisted Pair屏蔽双绞",
                  "str":"Suspend to Ram悬挂于内",
                  "svc":"Switched Virtual circuit交换虚电",
                  "svga":"Super Video Graphics Array超级影像阵",
                  "t1":" 支持24路PCM载波信号的美洲PCM标",
                  "tb":"TeraBit太",
                  "tb":"TeraByte太字",
                  "tc":"Transmission Convergence传输会聚子",
                  "tco":" 瑞典专业职业联",
                  "tcp":"Transfer Control Protocol传输控制协",
                  "tcp/ip ":"Transmission Control Protocol / Internet Protocol传输控制协议/网间通信协",
                  "tdm":"Time Division Multiplexing时分多路复",
                  "tftp":"Trivial File Transfer Protocol次要文件传输协",
                  "tia":"Telecommunication Industries Association 电信工业协",
                  "tiff":"Tag Image File Format标签式图像文件格",
                  "token-bus":" 令牌总",
                  "tron":"The Real-time Operating-system Nucleus实时操作系统中",
                  "tsmu":"Time-Sharing Multi-Use分时多用",
                  "tsr":"Terminate and Stay Resident驻留程",
                  "tty":"Teletypewriter电传打字",
                  "udp":"User Datagram Protocol用户数据报协",
                  "udt":"Uniform Data Transfer一致性数据传",
                  "uma":"Upper Memory Area上位内存",
                  "umb":"Upper Memory Block上位内存",
                  "uni":"User Network Interface网络用户端接",
                  "ups":"Uninterruptible Power Supply不间断电",
                  "url":"Universal Resource Locator资源统一定位",
                  "usb":"Universal Serial Bus通用串行总",
                  "utp":"Unshielded Twisted Paired非屏蔽双绞",
                  "uucp":"UNIX-to-UNIX CopyUNIX到UNIX的复",
                  "van":"Value-Added Network增值",
                  "vc":"Virtual Circuit虚通",
                  "vcd":"Video Compact Disc影",
                  "vci":"Virtual Channel Indicate虚拟通道标",
                  "vdsl":"Very-high-rate Digital Subscriber Line超高速数字用户线",
                  "vesa":"Video Electronics Standards Association视频电子标准协会(VL总线",
                  "vga":"Video Graphics Array影像阵",
                  "vi":"Virtual Interface虚拟接",
                  "vlan":"Virtual Local Area Network虚拟局域网",
                  "vldb":"Very Large Database超大型数据",
                  "von":"Voice On the Net网络语",
                  "vpi":"Virtual Path Indicate虚拟路径标",
                  "vpn":"Virtual Private Network虚拟专用",
                  "vr":"Virtual Reality虚拟现",
                  "vram":"Video Random Access Memory视频随机存储",
                  "vrml":"Virtual Reality Makeup Language虚拟现实标记语",
                  "vrml":"Virtual Reality Modeling Language虚拟现实建模语",
                  "vt":"Virtual Terminal虚拟终",
                  "w3c":"World Wide Web Consortium世界范围网联",
                  "wais":"Wide Area Information Service广域信息服务系",
                  "wan":"Wide Area Network广域",
                  "wap":"Wireless Application Protocol无线应用协",
                  "wbem":"Web-Based Enterprise Management基于Web的企业管",
                  "wdm":"Wavelength Division Multiplexing波分多路复",
                  "wintel":"Windows + Intel微软、英特尔(联盟",
                  "www":"World Wide Web万维",
                  "wysiwyg":"What You See Is What You Get所见即所",
                  "x.25":" 由CCITT提出的DTE至DCE间的接口协",
                  "xll":"eXtensible Link Language可扩展链接语",
                  "xml":"eXtensible Markup Language可扩展标记语",
                  "xms":"eXtended Memory Specification扩充内存规",
                  "xsl":"eXtensible Style Language可扩展样式语",
                  "y2k":"Year 20002000年问",
});

exports.words = words